industry:
    inputs:
        path-energy-balances: build/data/annual-energy-balances.csv
        path-cat-names: config/energy-balances/energy-balance-category-names.csv
        path-carrier-names: config/energy-balances/energy-balance-carrier-names.csv
    outputs:
        placeholder-out1:
        placeholder-out2:
    params:
        year-range: [2000, 2018]  # Start and end year for JRC data parsing
        steel:
            recycled-steel-share: 0.5  # % of recycled scrap steel for H-DRI
