industry:
  inputs:
    path-energy-balances: build/data/annual-energy-balances.csv
    path-cat-names: config/energy-balances/energy-balance-category-names.csv
    path-carrier-names: config/energy-balances/energy-balance-carrier-names.csv
  params:
    year-range: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
  setup:
    main-out-path: data/industry

