$schema: https://json-schema.org/draft/2020-12/schema
type: object
additionalProperties: false
properties:
    inputs:
        type: object
        additionalProperties: false
        description: Inputs are paths of prerequired files.
        properties:
            path-energy-balances:
                type: string
                description: |
                    Annual energy balance file.
                    Columns [cat_code,carrier_code,unit,country,year,value].
            path-cat-names:
                type: string
                description: |
                    Category mapping file.
                    Columns [cat_code,top_cat,sub_cat_contribution,sub_cat_1,sub_cat_2,jrc_idees].
            path-carrier-names:
                type: string
                description: |
                    Carrier mapping file.
                    Columns [carrier_code,carrier_name,hh_carrier_name,com_carrier_name,ind_carrier_name,oth_carrier_name].
            path-jrc-industry-energy:
                type: string
                description: |
                    JRC processed industry energy demand .nc file.
            path-jrc-industry-production:
                type: string
                description: |
                    JRC processed industrial production .nc file.
    outputs:
        type: object
        description: Outputs are paths for the files produced by the module.
    params:
        type: object
        additionalProperties: false
        description: Parameters allow users to configure module behaviour.
        properties:
            non-generic-categories:
                type: array
                description: "Specifies which JRC industry categories will be processed separately."
                uniqueItems: true
                items:
                    type: string
                    enum: ["Iron and steel", "Chemicals Industry"]
            steel-config:
                type: object
                additionalProperties: false
                description: "Parameters specific to the 'Iron and steel' industry category."
                properties:
                    recycled-steel-share:
                        type: number
                        description: "Share of recycled metal in the H-DRI steel process."
                        minimum: 0
                        maximum: 1
            generic-config:
                type: object
                additionalProperties: false
                description: "Parameters for default/generic category processing."
                properties:
                    final-energy-method:
                        description: |
                            Processing method for final-demand.
                            - "by priority": will take the carriers specified in "final-energy-carriers" in order of importance (first subtracts from second, etc.).
                            - "keep everything": will keep all the final carrier demands with no assumptions.
                        type: string
                        enum: ["by priority", "keep everything"]
                    final-energy-carriers:
                        type: array
                        description: "Final energy carriers to take, if relevant."
                        uniqueItems: true
                        items:
                            type: string
                    useful-demands:
                        type: array
                        description: |
                            Demands to select from 'useful' rather than 'final' energy consumption data.
                            Accepts any pre-processed JRC IDEES 'subsection' names.
                            Always subtracted from 'final' energy demand to avoid double-counting.
                        uniqueItems: true
                        items:
                            type: string
